### PR TITLE
restore cc0_html_rdfa() function

### LINKED ISSUE #114: Call to undefined method CreativeCommons::cc0_html_rdfa()
## Describe the bug
When I use the CC0 license for an image I can't post/preview a post/page as I get a critical error.
When I look in the logs I see:

`NOTICE: PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method CreativeCommons::cc0_html_rdfa()`

When I search for `cc0_html_rdfa` in your GitHub repo I indeed don't see any method for `cc0_html_rdfa`, so the call indeed doesn't work. I only see the [method being called here](https://github.com/creativecommons/wp-plugin-creativecommons/blob/09ce39511e40405186b5dac68c7f6b5cfad866f9/includes/class-creativecommons-image.php#L461).

## To Reproduce
1. Go to the media library
2. Open an image and add a CC0 license
3. Create a new post and use the image as featured image
4. Hit preview or publish
5. See error

## Expected behavior
Don't see error

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 76.0

### PR DESCRIPTION
**Pull request by hugosolar**
## Fixes
Fixes #114 by @siccovansas

## Description
This PR restore the function `cc0_html_rdfa()` which was previously removed on #76. 
I'm not completely sure if this function is needed but we can discuss about it. In the meantime, this shouldn't generate errors.
Tagging @ahmadbilaldev to get more feedback about this

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: includes/class-creativecommons.php [hunk 1]
```diff
@@ -996,6 +996,41 @@ public function sanitize( $input ) {
...
+	 *
+	 * @param  mixed $title_work
+	 * @param  mixed $attribute_url
+	 * @param  mixed $attribute_text
+	 */
+	public function cc0_html_rdfa( $title_work, $attribute_url, $attribute_text ) {
+		$result = '<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
+		<a rel="license"
+		href="http://creativecommons.org/publicdomain/zero/1.0/">
+		<img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" /></a>
```
Comment (TimidRobot) [inline includes/class-creativecommons.php:1010]: we must not have remote images (see #76 )

File: includes/class-creativecommons.php [hunk 2]
```diff
@@ -996,6 +996,41 @@ public function sanitize( $input ) {
...
+				<span property="dct:title">' . $attribute_text . '</span></span>';
+		}
+		$result .= '  has waived all copyright and related or neighboring rights to
+  		<span property="dct:title">' . $title_work . '</span>.'
+		/*
+		This work is published from:
+		<span property="vcard:Country" datatype="dct:ISO3166"
+		content="' . $country_code . '" about="' . $attribute_url . '">
+		' . $country_name . '</span>.
+		*/
```
Comment (TimidRobot) [inline includes/class-creativecommons.php:1030]: i don't see any value in keeping this comment

File: includes/class-creativecommons.php (hunk 1 above)
Comment (hugosolar) [reply includes/class-creativecommons.php:1010]: oh ok. I'll replace it with local images

**Comment by ahmadbilaldev** [comment]
I handled the cc0 license within the main function so there was no need for a standalone cc0 rdf function. Apparently an a faulty call is causing this problem which shouldn't be there. I think the better strategy should be to remove this function and all its calls.

**Comment by hugosolar** [comment]
> I handled the cc0 license within the main function so there was no need for a standalone cc0 rdf function.
> 
> Apparently, a faulty call on line `#461` in the image class is causing this problem which shouldn't be there. I think the better strategy would be to remove this function and all its calls.
> 
> Hence the problem of local images will be sorted out as well as the issue in question. Also, its implementation is not inline with the actual way licenses are being shown.

Thank you for your feedback @ahmadbilaldev I'm going to follow your suggestion 😃

**Comment by hugosolar** [comment]
Ok, so I removed the function call and the function itself.
@ahmadbilaldev would you have some time to review it?
